name: 24/7 Master Broadcast

on:
  schedule:
    # إعادة تشغيل العمل تلقائياً كل 5 ساعات لضمان عدم تجاوز حد مجانيات GitHub Actions
    - cron: '0 */5 * * *'
  workflow_dispatch:

jobs:
  broadcast:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Dependencies & Static FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          pip install --upgrade streamlink
          
          # تحميل وتثبيت نسخة FFmpeg Static المعزولة لتجنب انهيار الذاكرة
          wget https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz
          tar -xvf ffmpeg-release-amd64-static.tar.xz
          sudo mv ffmpeg-*-amd64-static/ffmpeg /usr/local/bin/ffmpeg
          sudo mv ffmpeg-*-amd64-static/ffprobe /usr/local/bin/ffprobe
          sudo chmod +x /usr/local/bin/ffmpeg /usr/local/bin/ffprobe

      - name: Run Broadcast Script
        env:
          RTMP_URL: ${{ secrets.RTMP_URL }}
          RTMP_KEY: ${{ secrets.RTMP_KEY }}
          CHANNEL_NAME: "TMNAA"
          DESTINATION: "restream"
        run: |
          chmod +x stream.sh
          ./stream.sh
